---
- name: 'Install packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ ufw_role_packages }}'
    apt_package_update_cache: true

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
