---
- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ ufw___packages }}'
    apt_srv_package_update_cache: true

- name: 'Config'
  ansible.builtin.import_tasks: 'config.yml'
