---
###############################################################################
# UFW Packages
###############################################################################

- name: 'Packages | install'
  ansible.builtin.apt:
    name: '{{ ufw_role_packages }}'
    state: '{{ ufw_role_package_state }}'
