---
###############################################################################
# Default
###############################################################################
# Confirm default settings are set to expected values and config loads without
# error; and group rules are applied before host rules.
#
# Tests:
# * ufw.service is enabled.'
# * incoming connections are denied by default.
# * outgoing connections are allowed by default.
# * SSH (22/tcp) incoming connections are allowed.
# * Rule ordering is correct (22 then 2222).
# * /etc/default/ufw IPv6=no when IPv6 is disabled for the host.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        ufw_host:
          - proto: 'tcp'
            from_ip: 'any'
            to_port: 2222
            direction: 'in'
            log: false
            comment: 'host rule after group rule'
platforms:
  - name: 'ufw-debian-12-default'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - 'NET_ADMIN'  # iptables (ufw)
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # ufw config is always removed on deployment.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
